# Generated by Django 3.2.9 on 2021-11-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_auto_20211106_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='GTIN',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
        ),
    ]
