# Generated by Django 3.2.9 on 2021-11-07 10:19

import django.core.validators
from django.db import migrations, models
import inventory_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_auto_20211106_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='GTIN',
            field=models.CharField(max_length=14, unique=True, validators=[inventory_app.validators.validate_GTIN]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='Name'),
        ),
    ]
