# Generated by Django 3.2.9 on 2021-11-07 15:21

from django.db import migrations, models
import inventory_app.models
import inventory_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_auto_20211107_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='GTIN',
            field=models.CharField(max_length=14, validators=[inventory_app.validators.validate_GTIN]),
        ),
        migrations.AlterField(
            model_name='product',
            name='shortest_expiry_date',
            field=models.DateField(default=inventory_app.models.Product.current_date, validators=[inventory_app.validators.validate_date_not_passed], verbose_name='Products expire at'),
        ),
    ]
